#:schema node_modules/wrangler/config-schema.json
name = "kiyota-coffee"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"] # THIS MUST BE PRESENT

pages_build_output_dir = ".open-next"

[vars]
NODE_VERSION = "22"